export const OPS = {
    BUILD: 0,
    STIR_TO: 1,
    STIR_FROM: 2,
    POUR: 3,
    SERVE: 4,
    ROLL: 5,
    CLOSE: 6,
    REPAY: 7,
    REPAY_VAULT: 8,
    FORWARD_PERMIT: 9,
    FORWARD_DAI_PERMIT: 10,
    JOIN_ETHER: 11,
    EXIT_ETHER: 12,
    TRANSFER_TO_POOL: 13,
    ROUTE: 14,
    TRANSFER_TO_FYTOKEN: 15,
    REDEEM: 16,
  }